apiVersion: v1
kind: Pod
metadata:
  name: podii
  labels:
    type: pod
spec:
  containers:
    - image: nginx
      name: c1
  initContainers:
    - name: c0
      image: nginx
      command: ["pwd"]