apiVersion: v1
kind: Secret
metadata:
  name: test-configmap
  labels:
    type: prod
data:
  db_passwd: aGVsbG8=



==================================================
     env from secret file
==================================================

