apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  labels:
    type: prod
data:
  db_passwd: aGVsbG8=



==================================================
     env from secret file
==================================================

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    type: prod
spec:
  containers:
  - name: c1
    image: nginx
    envFrom:
      - secretRef:
          name: test-secret


==================================================
     env from secret keys
==================================================

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    type: prod
  spec:
    containers:
      - name: c1
        image: nginx
        envFrom:
          - secretKeyRef:
              name: test-secret
              key: db_passwd



==================================================
     env from volumes
==================================================

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    type: prod
  spec:
    containers:
      - name: c1
        image: nginx
        volumes:
          - name: app-secret-volume
            secret:
              secretName: app-secret
