apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: test
spec:
  containers:
  - name: containers1
    image: nginx
    env:
      - name: whoami
        value: shashi
    ports:
      - name: web
        containerPort: 80
        protocol: TCP
  - name: containers2
    image: nginx
    env:
      - name: whoami
        value: shashi
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 81
        nodePort: 30036