apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
  labels:
    type: test
spec:
  template:
    metadata:
      name: pooo
      labels:
        type: pod
    spec:
      containers:
        - name: cooo
          image: nginx
  replicas: 3