apiVersion: v1
kind: Service
metadata:
  name: myservice-clusterip
  labels:
    type: clusterip
spec:
  type: ClusterIp  #if type is not mentioned then cluster IP will be considered by default
  selector:
    type: prod
  ports:
    - port: 80  #This is the outgoing port at the service. This is mandatory.
      targetPort: 80 #This is at the pod end, if this is not mentioned then below port section value will be considered. This is not an mandatory section.