apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-db-deployment
  labels:
    app: redis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      name: redis-db
      labels:
        app: redis-db
    spec:
      containers:
        - name:  redis-db
          image: nginx
        - ports:
            containerPort: 3432