apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: voting-app
    type: voting-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: voting-app
    spec:
      containers:
        - name:  voting-app-container
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80