apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      name: voting-app
      labels:
        app: voting-app
    spec:
      containers:
        - name:  voting-workerapp
          image: kodekloud/examplevotingapp_worker:v1