apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      name: result-app
      labels:
        app: result-app
    spec:
      containers:
        - name:  result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80