apiVersion: apps/v1
kind: Service
metadata:
  name: redis
  labels:
    app: voting-app
    type: cluster-ip-redis
spec:
  type: ClusterIP
  Selector:
    app: redis-db
  ports:
    - port: 6379
      targetport: 6379
