apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db-workerapp
    type: cluster-ip-postgress
spec:
  type: ClusterIP
  selector:
    app: postgress-db
  ports:
    - port: 3432
      targetPort: 3432
