apiVersion: v1
kind: Service
metadata:
  name: vapp-nodeport
  labels:
    type: nodeport
spec:
  type: NodePort
  selector:
    app: voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000