apiVersion: v1
kind: Service
metadata:
  name: result-nodeport
  labels:
    type: nodeport
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000